version: "3.1"

networks:
    bestscooter-network:

services:
    database-server:
        image: bestscooter.azurecr.io/database-server
        # image: database-test
        container_name: database-server
        ports:
            - 3306:3306
        restart:
            always
        networks:
            bestscooter-network:
        volumes:
            - ./database:/var/lib/mysql
        #     - ./sql:/docker-entrypoint-initdb.d
        environment:
            MARIADB_ROOT_PASSWORD: example
        #     MARIADB_USER: user
        #     MARIADB_PASSWORD: password
        #     MARIADB_DATABASE: database

    adminer:
        image: adminer
        restart: always
        networks:
            bestscooter-network:
        links:
            - database-server:database-server
        ports:
            - 8080:8080

    api-server:
        image: bestscooter.azurecr.io/api-server
        container_name: api-server
        links:
            - database-server:database-server
        ports:
            - 1337:1337
        restart:
            always
        networks:
            bestscooter-network:
        environment:
            NODE_ENV: simulation
            JWT_SECRET: 0693bb681da84b0d6556f315802b3773a356e86b3c2b2c8fe85002472ec02861
            OAUTH_CLIENT_ID: ab37ccfd44b552a7f961
            OAUTH_CLIENT_SECRET: 1bb0534a49e6243820daddb3e308a33b93b07c2e
            DATABASE_SERVER: database-server
            DATABASE_DATABASE: simulation
            DATABASE_USERNAME: user
            DATABASE_PASSWORD: password
            PORT: 1337
